### ISSUE TITLE
Windmill bearing doesn't work in claimed chunk

### ISSUE THREAD

**Issue by Novitia** [qwek1/All-of-Create#1]
Hello, today I found out that if you have a Windmill Bearing set up on one of your claimed chunks, the blocks tied to it will become unmovable. The issue gets solved if you unclaim the chunk of course, but it is quite bothersome.
![image_2024-02-25_064325204](https://github.com/qwek1/All-of-Create/assets/80666696/0eff972e-d2e5-4ad2-9a70-503064f84f79)

**Comment by qwek1** [comment]
I cant seem to reproduce the issue on my end but I have gotten a similar report recently so it should be an issue with the pack.
Did you modify the pack? And are you on singleplayer or a server?

![image](https://github.com/qwek1/All-of-Create/assets/133406949/2ccf7438-4bac-45fa-82ef-bfcc4f08b590)

**Comment by Novitia** [comment]
Single player, and I don't remember changing the modpack. Let me back up my world and reinstall the modpack !

**Comment by Novitia** [comment]
From testing, my world doesn't alllow me to start the bearings, but if I create a new world they work just fine.

**Comment by Novitia** [comment]
I found a solution for me, which is to turn off Claim Chunk Protection on my world 
![image_2024-02-25_184526672](https://github.com/qwek1/All-of-Create/assets/80666696/92144720-8e27-41b5-8aba-3f3e4296bfd4)

But the issue is that the new world I created DOES have it on and it still works.
![image](https://github.com/qwek1/All-of-Create/assets/80666696/2e2702d8-10d7-48d2-a0cd-8661d62494b3)

Maybe the fact the world was made in 2.4.2 ? But the warning to backup the worlds is for older versions updating to 2.4.2 and not from 2.4.2 to 2.5+ right ?

**Comment by qwek1** [comment]
It works for me even when Claimed Chunk Protection is on, ill try to reproduce the issue on my end.
There will never be issues updating your Modpack, however its always safer to backup.

**Comment by qwek1** [comment]
Please report this to the Open parties and claims developer, ill report it to them if I manage to reproduce the issue on my end

**Comment by Novitia** [comment]
Gladly ! Do you know which mod version 2.4.2 had for Open parties and claims ?

**Comment by qwek1** [comment]
open-parties-and-claims-forge-1.19.2-0.20.4.jar which is latest
