### ISSUE TITLE
Texture error

### ISSUE THREAD

**Issue by GuanchoTalarga28823** [qwek1/All-of-Create#10]
Hello, i have an issue whit the texture pack. I just download the modpack yesterday and when i launched the modpack, the first thing that i see is what the texture pack doesn't load correctly. PLS i need ur help

**Comment by qwek1** [comment]
Could you provide a screenshot?

**Comment by GuanchoTalarga28823** [comment]
> Could you provide a screenshot?

Shure
Resurcepacks in minecraft
![image](https://github.com/qwek1/All-of-Create/assets/167936356/adbca63d-514d-4823-8ef6-6f544ec2d69b)
![image](https://github.com/qwek1/All-of-Create/assets/167936356/d3ccdfa9-605e-42d5-a16d-76a61d271deb)
Resurcepacks in folder
![image](https://github.com/qwek1/All-of-Create/assets/167936356/96128d59-0a22-434c-be20-fec11c71622f)
In game hud and another issues
![image](https://github.com/qwek1/All-of-Create/assets/167936356/3c43888d-0c5f-4d4d-a2df-6bd1320ad3e8)
![image](https://github.com/qwek1/All-of-Create/assets/167936356/8e0e4582-a5f0-454e-bd97-2e9123dbf9ea)
![image](https://github.com/qwek1/All-of-Create/assets/167936356/cea74579-309e-4d0a-b569-30e08adec7d9)
![image](https://github.com/qwek1/All-of-Create/assets/167936356/02a20052-43f2-4f22-a1d8-a6cb4eec35c1)



Im playing in 1.9.2 - 43.3.5 Forge if u ask.

**Comment by GuanchoTalarga28823** [comment]
> Could you provide a screenshot?

Hi, i fix it i dont know why but when i unzip the modpack for some reason windows delete the create texture file

**Comment by qwek1** [comment]
How did you install the modpack?

**Comment by GuanchoTalarga28823** [comment]
> How did you install the modpack?

First i download server modpack, then i copy all the carpets from the singleplayer modpack and then i paste in the server modpack and click in replace all archives

**Comment by qwek1** [comment]
Your using a modded launcher to install the modpack? Or the Vanilla one

**Comment by qwek1** [comment]
no response will close for now
