### ISSUE TITLE
Quest Reset

### ISSUE THREAD

**Issue by MateoBarbato** [qwek1/All-of-Create#11]
I had a energy cut-down and when re-opening the game all the quest acomplished were back to the beggining, even re-doing the tutorial. Might be mod related, just wanted to let you guys know

**Comment by qwek1** [comment]
Yeah thats because your game didnt save properly when your power went out 😓 

Nothing I can do unfortunately, but thanks for the report anyways 🙏

**Comment by MateoBarbato** [comment]
Hii! Thanks for the quick response, I found a solution for and if future people get this issue .
Looking a little bit more on the quest mod FTB QUESTS. There is a command to manually give yourself the achievements.
