### ISSUE TITLE
'Are they just gears, but 100%' Message

### ISSUE THREAD

**Issue by hectogm4b** [qwek1/All-of-Create#12]
Hello, I've been playing for several days and since today I get that message (Are they just gears, but 100%), what does it mean and how can I remove it? Thank you very much!

**Comment by qwek1** [comment]
wdym? 😅 
Could you provide a screenshot please? 😄

**Comment by hectogm4b** [comment]
> wdym? 😅 Could you provide a screenshot please? 😄

![image](https://github.com/qwek1/All-of-Create/assets/17494791/0d089225-3633-4419-b7ee-1cb8abb851eb)

😅😅😅

**Comment by qwek1** [comment]
oh! Thats just your quest being pinned, you can go into the questbook and find that quest to unpin it!

**Comment by hectogm4b** [comment]
> oh! Thats just your quest being pinned, you can go into the questbook and find that quest to unpin it!

Oh, sorry, Im so silly, thanks <3

**Comment by qwek1** [comment]
no worries at all!
