### ISSUE TITLE
Enchantment Industry not showing text descriptions

### ISSUE THREAD

**Issue by JoseConder** [qwek1/All-of-Create#13]
Hello, when using enchantment industry there apears to be a bug where text wont show, in its place shows the object code for it.
This applies to the ponder and achievements.
I downloaded this modpack to play alongside a streamer and it seemed that he also had this problem.
![a](https://github.com/qwek1/All-of-Create/assets/123893636/09550c75-1862-4be0-a025-46c1aa5f1593)
![aa](https://github.com/qwek1/All-of-Create/assets/123893636/7765d06a-218c-48a0-b2d3-c5c576f96d68)
![aaa](https://github.com/qwek1/All-of-Create/assets/123893636/5f636e55-bb89-4f85-ae7a-2122c049b271)

**Comment by qwek1** [comment]
Ill look into it, thanks for reporting!

**Comment by qwek1** [comment]
will be fixed in the next update (v3.1)
