### ISSUE TITLE
Mods are missing

### ISSUE THREAD

**Issue by AgusSoto03** [qwek1/All-of-Create#14]
When I download the modpack and go to the mods inside the downloaded folder, I see that there are no mods, there is only the memoryleakfix, Does anyone know how to solve it? A friend tried to download it and the same thing happened to him

**Comment by qwek1** [comment]
You need to use an modded launcher to install the pack

from the LPS discord:
We recommend [ATLauncher](https://atlauncher.com/download)
Install and run the setup, then open the program.
Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials.
Go to the Packs tab on the right, then click "Curseforge" on the left.
Search the modpack you wish to download.
Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen.
Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.
