### ISSUE TITLE
Render chunks

### ISSUE THREAD

**Issue by markelrlopez** [qwek1/All-of-Create#15]
I'm having problems with rendering chunks, whenever I go too fast the chunks take so long to load that the world appears to crash.

**Comment by qwek1** [comment]
Follow this
https://github.com/LunaPixelStudios/Better-MC/wiki/Performance-Guide
If issue persists please install the Spark mode and create a profiler while producing the lag

**Comment by alca259** [comment]
Disable mods "Better chunk loading" and "Chunk sending" is works for me on my server
