### ISSUE TITLE
Issue with the Creating Space.

### ISSUE THREAD

**Issue by Monogatari-Fan** [qwek1/All-of-Create#18]
Methane, which is obtained after processing hydrogen with a chemical synthesiser, is needed to go into space. The problem I have is that the chemical synthesiser is nowhere to be found. I don't care about going into space, the problem is that aluminium is only available on the moon. 
![2024-05-02 01_18_14-All of Create](https://github.com/qwek1/All-of-Create/assets/168689062/e0c6425b-b341-48e9-9bae-d838e63050a7)

**Comment by qwek1** [comment]
I don't think you need it to go to space, you can visit their Discord for a guide on the mod.
https://discord.gg/8TJ6r7pbbd

**Comment by Monogatari-Fan** [comment]
> I don't think you need it to go to space, you can visit their Discord for a guide on the mod. https://discord.gg/8TJ6r7pbbd

Thanks, I'll try there
