### ISSUE TITLE
Request of mods in the modpack "All of Create"

### ISSUE THREAD

**Issue by CalpDnc** [qwek1/All-of-Create#21]
I would love you to add storage drawers, FXNT BitsNBobs, and Waystones to the modpack "All of Create".
Thank you.

**Comment by CalpDnc** [comment]
Also Construction Wands could be good too.

**Comment by CalpDnc** [comment]
Framed Blocks is pretty good either.

**Comment by qwek1** [comment]
will take them into consideration, thanks for the suggestions
