### ISSUE TITLE
Mobs/entities are not despawning/dying in nearby chunks

### ISSUE THREAD

**Issue by JTostitos** [qwek1/All-of-Create#22]
I have noticed on an AOC server that I am running, that mobs/entities that are a few chunks away become frozen. For Example:

1. Phantoms in nearby chunks will freeze in the air. Going back to the chunk with the frozen phantom will not unfreeze the phantom unless your player is at a higher elevation.

2. Shooting an arrow into the sky, the arrow freezes in the sky. It will not come down unless the player moves to a higher elevation.

3. Iron Farm. In AOC, I can stand in a nearby chunk, and the golems will freeze toward the bottom of the farm. In Vanilla with only 1 mod - freecam (for demonstration purposes) - this does not happen. [AOC Video](https://github.com/qwek1/All-of-Create/assets/17661536/9578cd66-96b2-47e8-83e2-a5ff8e430d58) vs [Vanilla Video](https://github.com/qwek1/All-of-Create/assets/17661536/8f6fba2c-65f4-4f0a-8520-d7f393364ca6)

4. Mobs that would normally despawn many chunks away in vanilla, do not despawn in AOC. The look frozen and sometimes have a weird spinning animation.

What mod is altering the vanilla mob/entity spawning/despawning mechanics? Maybe its a mod that is altering render distance stuff? **Of Note:** this happens in the AOC modpack without any changes made to the mods.

AOC v3 1.19.2

**Comment by qwek1** [comment]
Entities becoming frozen an intended feature from the Doespotatotick mod to help with performance, but it will be removed next update. 

Not sure whats causing mobs to spin though, but theres another mod called Despawn Tweaker that does modify the despawning mechanic

**Comment by JTostitos** [comment]
Thanks
