### ISSUE TITLE
Conflict between recipes

### ISSUE THREAD

**Issue by 22858** [qwek1/All-of-Create#23]
I attempted to make some copper wires from Create New Age by processing the copper plates with a mechanical saw only to acquire copper wire from Create Train Additions. 
They share the same recipe, but the recipe from Create Train Additions seems to have higher priority
![image](https://github.com/qwek1/All-of-Create/assets/153057608/9fa23e7a-bdbb-4585-b740-51c427da6e56)
Does that mean I can never craft New Age's copper wires? Or is there a solution?

**Comment by 22858** [comment]
Now I know what to do, sorry for the silly issue😭

**Comment by qwek1** [comment]
Sorry for the late response, I have been busy with exams 😅 

I was going to look into the issue today but seems like you have already figured something out, what did you do to resolve the "issue" if you dont mind me asking? 😅

**Comment by 22858** [comment]
I dragged the items from JEI to an item filter to filter the recipe. I didn't know this before😂
