### ISSUE TITLE
[Recipe Adjustments] Create: Garnished conflictions

### ISSUE THREAD

**Issue by DakotaPride** [qwek1/All-of-Create#26]
With Create: Garnished recently being added, I thought that I would point out some changes that should be made to fix certain issues that arise.

1. Crushing Scorchia - Dreams & Desires also has a Scorchia crushing recipe. Adjusting this recipe to produce Brittle Dust, Coal Pieces, and Cinder Flour would fix one of the recipes not working. (perhaps with varying chances given the amount of items that would be produced)
2. Crushing Limestone - TFMG has a crushing recipe for Limestone to provide Limesand, which was recently brought up in the Luna Pixel Studios discord. Similar to the Scorchia recipe, adjusting this to produce both Limesand, Crushed Salt Compound, and perhaps smaller chances of Iron/Zinc nuggets.

I think those are the only recipe incompatibilities. I'm not sure how exactly you go about changing recipes (if at all), so apologies if this would be inconvenient to implement.

**Comment by qwek1** [comment]
will be fixed in v3.3, thanks for reporting!
