### ISSUE TITLE
Iron Chest Not Working

### ISSUE THREAD

**Issue by AndresImery** [qwek1/All-of-Create#28]
When trying to craft an Iron Chest with an oak chest or regular "chest" it doesn't work with the same recipes that appear in JEI.

**Comment by qwek1** [comment]
could you send a screenshot of you trying to craft it, and the recipe shown in JEI?

**Comment by Commando125** [comment]
Hey there! Was looking into issues with this modpack before playing it.

You have to craft the chest with a redstone torch to make it a sophisticated chest, and then craft that with 8 iron ingots surrounding it.
