### ISSUE TITLE
Issue with crushing wells recipies

### ISSUE THREAD

**Issue by Waldito33** [qwek1/All-of-Create#29]
There is two different recipies for inputing magma block into crushing whells. One is from create and gives u magma balls and netherrack and the other one is from an addon called create things and misc and gives u scoria and magma fragment?.
The issue is that there is no way to select a recipie or filter recipies in the crushing whells like there is in other create machines. Therefore the only output the crushing whells give me is the scoria one, and is imposible for me to get the magma ball one.
Is there anything u can do about it ? or do u know how could i sollve this?
Im using the mod pack in a server in athernos so i have no way to remove mods, which could possible be a solution, to remove the things and misc addon, but as i say i cant. 
Thank u for ur time and ur work

**Comment by qwek1** [comment]
I would suggest reporting this to the Create things and misc devs instead, ill remove one the recipes from the modpack soon though

**Comment by qwek1** [comment]
fixed in v3.5, will be released soon
