### ISSUE TITLE
create_enchantment_industry:crafting/disenchanter do not accept enchantment weapons, armor, books

### ISSUE THREAD

**Issue by elislavkat** [qwek1/All-of-Create#30]
![image](https://github.com/qwek1/All-of-Create/assets/64079137/e8411329-1ce4-4078-a4b3-4c34320ebecc)
Hello. This is only 4 things this can "melt"
is it correct or bug ?

**Comment by Commando125** [comment]
I tried putting enchanted books, weapons, and armor in there on my end and it worked fine. The JEI page is misleading on what the disenchanter can accept or not.

**Comment by elislavkat** [comment]
> I tried putting enchanted books, weapons, and armor in there on my end and it worked fine. The JEI page is misleading on what the disenchanter can accept or not.

the problem was in: manually putting items on disenchanting block is doing nothing. It works only by belts.. Strange..
