### ISSUE TITLE
No automated copper

### ISSUE THREAD

**Issue by CalpDnc** [qwek1/All-of-Create#34]
You know that the main elements of Create is brass and andesite getting the andesite can be automated but brass is made out of copper and tuff not being automated makes copper not automated. I think this is a large problem.

**Comment by CalpDnc** [comment]
You can add Create: Metalwork as a new mod but it still doesn’t automate copper but you can double all metals. I prefer you watching the video of polartt on YouTube. The link: https://youtu.be/NiFLUue9SQc?si=xMTKreeAeN_9BOX4

**Comment by qwek1** [comment]
I currently do not have plans to let players automate copper, that might change in the 1.20.1 version of the modpack thats being worked on but for now there are no plans to do so for 1.19.2.

There are plans to have ore processing on the 1.19.2 version of the modpack, but it would not be with the Create: Metalwork mod.

**Comment by Killerwatz872KiwiArmy** [comment]
there is a way to automate copper currently by using caramel milkshake and lava to create verdium which can be crushed using crushing wheels to make crushed copper ore and copper nuggets
