### ISSUE TITLE
Excavation Drill does not work on a multiplayer server

### ISSUE THREAD

**Issue by Fullgor** [qwek1/All-of-Create#36]
Hello,
The Excavation Drill from the mod _Create: Dreams and Desires_ does not work on a multiplayer server: with the tool in hand, it is impossible to break any bloc; the bloc breaks then reappears instantly. There is no such problem with a classical pickaxe.
The weird thing is that the drill works perfectly in solo, so it may be a server configuration issue.

Tested on two different servers, one hosted on a third party host, and one hosted locally using the server setup downloaded directly from curseforge, without touching the initial configuration. Both have the same problem.

AoC version : v3.5HF

**Comment by qwek1** [comment]
issue with the current version of the Create: Dreams & Desires mod, will be fixed once that mod gets updated in the pack
