### ISSUE TITLE
Server files not working on some computers

### ISSUE THREAD

**Issue by SuperSmashGame** [qwek1/All-of-Create#37]
Yesterday, I tried installing the server files for AoC v.3.5HF. At first, it didn't work on my desktop (I included a log file from today that has the same error). Then I tried on my laptop, and it worked 1st try.

One difference between the two is that my desktop has Java 22, and my laptop has Java 19 (idk if that might be the cause of the issue).

[latest.log](https://github.com/user-attachments/files/16403756/latest.log) <-- Desktop logs
(If you need the laptop logs as well, I can provide them)

**Comment by qwek1** [comment]
Use Java 18

**Comment by SuperSmashGame** [comment]
So the question is, how do I point the server towards Java 18 instead of 22 ? I still need the latter to play newer versions of MC

**Comment by SuperSmashGame** [comment]
Tried to modify it, by replacing the "java" in the User JVM Args variables from options.txt with the path to my JDK17, no luck this far. Also tried tampering with the JAVA variable, nothing neither. Tried on both, nothing. With or without "s, nothing.
Now's probably not the time to worry about that, since you're on vacation, so I'll try to setup a normal forge server with the mods, configs, libraries etc. Thanks either way ! =)

**Comment by qwek1** [comment]
here's a guide for installing Java on the serverpack if you still need it : https://github.com/chorbintime/LPS-readme/wiki/1.19.2#video-guide
