### ISSUE TITLE
Pumpjuck base is broken

### ISSUE THREAD

**Issue by Antonhsusishere** [qwek1/All-of-Create#38]
Read the title I tried to make a pumpjuck I found a deposit I did everything right and the pumpjuck base just did find the deposit for no reson
![17231982214219195975586430728244](https://github.com/user-attachments/assets/9f7196de-a743-4207-8bea-38311483b6c1)
![17231982535961894143494906412279](https://github.com/user-attachments/assets/49059bcf-2388-481e-93ba-23a242fac9fa)

**Comment by qwek1** [comment]
report it to the create: tfmg devs
