### ISSUE TITLE
Canary Cached BlockState Flags are disabled

### ISSUE THREAD

**Issue by aduatl** [qwek1/All-of-Create#4]
[debug.log](https://github.com/qwek1/All-of-Create/files/14620189/debug.log)
[latest.log](https://github.com/qwek1/All-of-Create/files/14620190/latest.log)

Whenever I try loading up the server. It gives me this error
![image](https://github.com/qwek1/All-of-Create/assets/163589711/563da330-225a-41f2-8e38-858b2f727a54)
I don't know what is causing it because everything was working normally the night before.

**Comment by aduatl** [comment]
[debug.log](https://github.com/qwek1/All-of-Create/files/14620632/debug.log)
[latest.log](https://github.com/qwek1/All-of-Create/files/14620633/latest.log)

**Comment by qwek1** [comment]
resolved will close now

**Comment by trickhammer** [comment]
Non-programmer here.  I receive the same "Canary Cached Blockstate Flags are Disabled!"  Apparently this issue is resolved but how?  Do I need to do anything?  Thanks!

**Comment by qwek1** [comment]
That message isnt the issue, what does it say when you try to connect to
the server? The issue for the other person was just them not port fowarding
properly iirc, so make sure you have done that.
