### ISSUE TITLE
Elytra not being able to get 

### ISSUE THREAD

**Issue by Ffgcfdjh** [qwek1/All-of-Create#40]
I was Exploring the end and found a end city with a ship I went to it to get a elytra and I broke the item frame and it just kept falling then Teleporting back to the start again after that I tried it on another world and elytras just Disappear from Inventory and if in the world will be unable to pick up hopefully it can be fixed and yes I reinstalled it and tested it again

**Comment by Killerwatz872KiwiArmy** [comment]
Elytra's are banned on the modpack. it's to force you to use jetpacks

**Comment by qwek1** [comment]
You can enable them back through the item obliterator config.
