### ISSUE TITLE
Dragon's Breath Fluid

### ISSUE THREAD

**Issue by themightyspoon26** [qwek1/All-of-Create#41]
There are two mods conflicting in this modpack: Create Garnished and Create Central Kitchen. When I attmempt to put dragon's breath bottles into an item drain, the fluid it creates has the tag from Create Central Kitchen. Unfortunately, I need the dragons breath bottle to turn into the fluid from Create Garnished but it always turns into the wrong fluid. Is there a way to prioritze one fluid going into the item drain over another?

**Comment by Killerwatz872KiwiArmy** [comment]
have you tried using filters?

**Comment by themightyspoon26** [comment]
Item drains don't have a slot for filters. You have to right click the bottles of dragon breath into the drains and that always creates the incorrect fluid. If I were to use a filter on a basin, is there a way I can blacklist everything but the correct fluid from entering the basin?

**Comment by Killerwatz872KiwiArmy** [comment]
with item filters yes

**Comment by themightyspoon26** [comment]
When I use the item filter on a basin, it doesn't stop fluids from going into the basin, it only makes it so whatever the filter is set to is the crafting recipe the basin will produce.

**Comment by themightyspoon26** [comment]
![Base Profile Screenshot 2024 08 30 - 16 16 41 01](https://github.com/user-attachments/assets/155a9653-224d-4f96-a355-a8e93ca72115)

**Comment by Killerwatz872KiwiArmy** [comment]
i'm trying to solve this now in a singleplayer world. give me an hour or two

**Comment by Killerwatz872KiwiArmy** [comment]
yeah after testing different methods including filtered pipes, item filters on both basins and filtered pipes and seeing if i could somehow mix it into it's counterpart there is no way to get the garnished version. can't be added to backpack tanks either to try bucketing it. can't be transformed in create tanks. essentially it's a dead recipe for survival

**Comment by themightyspoon26** [comment]
That sucks, thanks for the help regardless.
