### ISSUE TITLE
Broken jei / not showing recipes

### ISSUE THREAD

**Issue by KonoACda** [qwek1/All-of-Create#42]
Am playing on the fabric version of the modpack (v3) and there are a lot of recipes like straight up not showing like how to make steel for example or how to make andesite casing using world interactrion or even using a deployer. Like you can't see anyyyy of the use recipes of machines when pressing ( U ) on an item or even a machine which makes  the game just annoying to play not nowing how to make stuff or that you can actully automate them using machines. and there are also duplicates of the same ores. like why not just disable those

PLEEEEEEAAAAASEEEEE FIXXX ITTTTTT.

![2024-08-31_04 41 15](https://github.com/user-attachments/assets/9eac3e02-90e8-4029-9332-94e85f9bf267)

![2024-08-31_04 42 20](https://github.com/user-attachments/assets/3da24308-2afd-40fd-b4ce-f22bba81fdae)

**Comment by qwek1** [comment]
replace REI with EMI, REI is broken
