### ISSUE TITLE
Elytra bugged 

### ISSUE THREAD

**Issue by Meilo14** [qwek1/All-of-Create#45]
The elytras are bugged, when you break the frame where they are located, they remain on the ground without being able to pick them up and this appears in the server console:
![error 1](https://github.com/user-attachments/assets/cec40d3e-fbd4-4ee3-a6fa-a09250b625f8)

**Comment by Meilo14** [comment]
On singleplayer happen too

**Comment by qwek1** [comment]
Elytras are disabled on the modpack, you can enable them back through the item obliterator config.

**Comment by Meilo14** [comment]
ty man
