### ISSUE TITLE
Factory Must Grow and Tipsy n' Dizzy have same error message

### ISSUE THREAD

**Issue by KitsuKatsu333** [qwek1/All-of-Create#47]
These error messages appeared for the casting basin at first, after attempting to use the multiblock furnace from the factory must grow and suddenly losing its function (only held either coke or the materials to be processed, dupes anything else). Then when trying to cast the liquid already in there from previous attempts, this message appeared and it did not cast anything.

I had assumed this was a bug with the factory must grow, which I wasn't too upset with not being able to fully use. However, this also happened after making the fermentation barrel, which I had plans for lol
![2024-10-08_00 14 52](https://github.com/user-attachments/assets/55b40865-f42d-43fd-a66b-b7434d6dfb31)
![2024-10-08_00 14 49](https://github.com/user-attachments/assets/22d8826f-6dbb-47df-adb0-1cdcd51fa224)

**Comment by qwek1** [comment]
Should fix yourself by waiting for a bit
