### ISSUE TITLE
The Factory Must Grow machines not outputting resources

### ISSUE THREAD

**Issue by KBarPar** [qwek1/All-of-Create#51]
I have made steel with TFMG machines with no problems, but when I tried to recently, the machines would take the resources in and spit out nothing in return. The coke oven fixed itself when I picked it up and put it back down, but when I tried to make steel through the basin, it would take in the molten steel and keep refreshing as though it had finished making an ingot, but there was no ingot anywhere.
Could just be a server issue, could just be a skill issue, but I swear that it has worked in the past and now it's just stealing my resources. I'll try again tomorrow, but im just too tired to do any further testing rn

**Comment by qwek1** [comment]
Try updating the Create: TFMG mod, if that does not fix the issue then plesae report it the mod developers instead
