### ISSUE TITLE
Elytra Config Problem

### ISSUE THREAD

**Issue by NevQuinzel** [qwek1/All-of-Create#52]
I am admittedly new to using mods and am having issues with re-enabling the elytra. The option to config does not light up like it does for other mods. What are other steps I can take to re-enable the elytra as I wanted to try out the crafting recipe with the elytra.

**Comment by qwek1** [comment]
Do it through the config folder in game files, not all configs are supported through the ingame editor.

Head into your modded launcher then `open file location > open "config" folder > item_obliterator.json5` to locate it

**Comment by NevQuinzel** [comment]
Thank you so much!!! got it working now!!
