### ISSUE TITLE
Game Freezes After 10-20 Minutes and is Unplayable after

### ISSUE THREAD

**Issue by AgWordSmith** [qwek1/All-of-Create#55]
Every time I load up a single player world I play for 10 minutes and the game freezes, I have audio but the screen is just frozen. 
I have already updated my Drivers. Completely Clean Install too. 

I have an Intel Iris Graphics card, Using a Surface Pro 7. I am able to run other LunaPixel Packs with out problems.

Here is my Log from the the last time I played the mod pack.
Edit: put it in a text file for you : 
[latest.log](https://github.com/user-attachments/files/17724081/latest.log)

**Comment by qwek1** [comment]
please follow the LPS performance guide, https://rpg.prominence.wiki/performance-guide
