### ISSUE TITLE
Problems with block placement.

### ISSUE THREAD

**Issue by Ol-Scruffy** [qwek1/All-of-Create#6]
Hi, I just downloaded the most recent update for All of Create on Curseforge and several blocks including stairs, ladders, iron rods (and probably more) only face one direction when placed. It doesn't matter which direction I am facing or if I shift-click. Nothing seems to work. How do I fix this?

**Comment by qwek1** [comment]
That is most likely because the rotation lock from Quark is enabled, try pressing k to disable it.

**Comment by Ol-Scruffy** [comment]
I will give that a shot for sure. Thank you. :)

**Comment by Ol-Scruffy** [comment]
That was absolutely correct. It shares the same keybind with turning off shaders, so I had activated it without even knowing. Thanks again. :D
