### ISSUE TITLE
Is there a tutorial on how to make a multiplayer server on a local pc?

### ISSUE THREAD

**Issue by krestenub** [qwek1/All-of-Create#62]

**Comment by qwek1** [comment]
# Paid Method
**We suggest renting a server from Bisect Hosting:** 
**Approx. $10 - $25** a month depending on what plan you choose. You can also get **25% off** with Code **LunaPixel**.

Go [here](<https://www.bisecthosting.com/LunaPixel>) and order a plan which fits you. We suggest **1GB** per player but nothing lower than **4GB** as the server needs at least **3GB** to run. 

**Go to <#821713819536719873> for more Info!**
  
# Free Method
To host a server on your own computer, [read the selfhosting guide](<https://github.com/chorbintime/LPS-readme/wiki>). 
This guide goes over how to install, create, and launch a free Minecraft server on all operating systems (MacOS, Linux and Windows). The guide also guides you through installing Java and optimizing your server for better performance.
