### ISSUE TITLE
Minecraft Crash Upon Launch

### ISSUE THREAD

**Issue by EliasUnv** [qwek1/All-of-Create#7]
I installed the modpack on AtLauncher, launched it, and it crashed. Log is provided in a Google Document below.
https://docs.google.com/document/d/11XSJE8I-e7QZ591KbczPIHRm0sG4B21YJvgcZVK0mdg/edit

**Comment by Raigass** [comment]
try
1. Install the Zulu JDK 17.0.1+12 arm64 build of Java:
Direct download: https://www.azul.com/core-post-download/?endpoint=zulu&uuid=7eb8ee44-ab7f-4afb-9e42-32bd76416400 
2. Download/Install ATLauncher or Prism Launcher (CurseForge Launcher is known to cause issues)
3. In Instance settings > Java, manually specify the following Java path: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
4. If using ATLauncher, Disable "Use Minecraft-bundled JDK"
5. Launch the game

**Comment by EliasUnv** [comment]
I've followed steps 1-3, but I can't figure out where the option to disable "Use Minecraft-bundled JDK" is. I'm using ATLauncher.

**Comment by qwek1** [comment]
go to instances, where the pack is and go to the settings tab, then in the Java/Minecraft tab

**Comment by EliasUnv** [comment]
<img width="1195" alt="Screenshot 2024-03-31 at 14 00 15" src="https://github.com/qwek1/All-of-Create/assets/150937362/1da6ca71-6131-42f6-9935-ad74bd57ed24">
Where?

**Comment by qwek1** [comment]
should be the "use Java provided by Minecraft"

**Comment by EliasUnv** [comment]
It still doesn't launch. Is there another problem?

**Comment by qwek1** [comment]
Could you send the new logs please?

**Comment by EliasUnv** [comment]
Sorry it took so long
Launch 1: Unupdated
Launch 2: Updated
https://paste.atlauncher.com/view/175c6754-9eb4-4146-8fbb-faf8c7707e5e

**Comment by qwek1** [comment]
sorry for the late reply, was busy
It seems to be an issue with Fancymenu now, please report it to the developers
Might be an Mac issue but im not familiar with Mac unfortunately

**Comment by EliasUnv** [comment]
Thanks :)
