### ISSUE TITLE
FTBquest: unable to open Quest GUI

### ISSUE THREAD

**Issue by Meilo14** [qwek1/All-of-Create#8]
I had an error when playing the all of create mod pack, any version of the mod gives me the same error.
One of the problems is the FTBquest, I attach a photo of the error, it also does not give me the quest book.
The other problem is the JEI, since when I press the key assigned to the recipes, it does not appear.
![ftb problem](https://github.com/qwek1/All-of-Create/assets/82753478/1f217932-6c1b-4fbf-b018-fa5552e11bbf)

ONLY HAPPENS IN MULTIPLAYER.

**Comment by qwek1** [comment]
Your server is installed incorrectly, your missing the configs. Please upload the configs folder to your server from the serverpack

**Comment by Meilo14** [comment]
After or before of instalation

**Comment by qwek1** [comment]
just make sure the server is down when your uploading the files and its fine, you dont need a fresh installation

**Comment by Meilo14** [comment]
ok, dont run. 
What config folders u mean?
![folders](https://github.com/qwek1/All-of-Create/assets/82753478/6bcc109d-b639-46d2-b506-c6e2444b99c2)

**Comment by Meilo14** [comment]
I have transferred the config folder of the mod pack to that of the server, then I have uploaded it to the VM and I have turned on the server, but when I enter I get the same error, it is the first time I have created a server in this way and it is a little confusing xD

**Comment by Meilo14** [comment]
![folders](https://github.com/qwek1/All-of-Create/assets/82753478/a70b15ad-59ac-4769-8d6b-1b9ac0aa81ae)
red or blue? sry, im so dumb

**Comment by Meilo14** [comment]
![server](https://github.com/qwek1/All-of-Create/assets/82753478/9cab1838-0263-440a-b82e-055d322e12bc)
thats the server

**Comment by qwek1** [comment]
yes upload the config folder from the serverpack to your server

**Comment by Meilo14** [comment]
Once the server is installed, I transfer all the servermodpack files and I still get the same error :(

**Comment by qwek1** [comment]
did you use the serverpack's mods folder too?

**Comment by Meilo14** [comment]
Could the error be because I am installing the server.jar together with the serverpack mods? i upload the jar file along with the folders and then execute.

**Comment by Meilo14** [comment]
Should I try to install the server.jar alone and then transfer the files to it?

**Comment by Meilo14** [comment]
Before wanting to play this modpack, I installed create astral and installed it without any problem, but it was quite difficult for my friend and I, and to try something simpler and play at the same time as a youtuber, we decided to install this one, and no We know why this error occurs.

**Comment by santicapone** [comment]
i had a error with the shield, when i use the shield crash and drop this error java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is

**Comment by Meilo14** [comment]
And in answer to your question, yes, I used the mods folder of the mod pack, and when I saw that it didn't work, I tried to put the one generated by curseforge in the instance and it didn't work either.

**Comment by Meilo14** [comment]
I'm trying to put blocks from any mod and nothing works. It looks like you are installing something wrong. The server.jar is provided in the serverpackmod, and I have installed it like the astral but here is something I am failing

**Comment by Meilo14** [comment]
I have tried to install the server only provided by the server pack and it has not generated any mods or config folder, maybe it is the wrong server?

**Comment by Meilo14** [comment]
https://piston-data.mojang.com/v1/objects/f69c284232d7c7580bd89a5a4931c3581eae1378/server.jar

**Comment by qwek1** [comment]
I would suggest setting up a Forge 1.19.2 43.3.5 server first, then once thats running; shut it down and upload the mods and configs folder onto the server. 

The serverpack uses powershell to run the server not server.jar

**Comment by Meilo14** [comment]
ok dude, ty for ur time, i create the server in a folder in my desktop with the powersell and it create the server alone 🥶. im uploading that to my VM, i hope it works, if you want a donation, give me ur paypal😉❤

**Comment by qwek1** [comment]
no need for donations, js lmk whether it works or not 😄

**Comment by Meilo14** [comment]
dont work xD

**Comment by qwek1** [comment]
whats the issue now?

**Comment by Meilo14** [comment]
Once I have started the powershell, it has created the server, I have stopped it and I have passed all the content to my VM, I have started it with the command java -Xmx6G -Xms1G -jar server.jar and I get errors. When you start the server again, it starts but it seems to be in vanilla.
![issue 3](https://github.com/qwek1/All-of-Create/assets/82753478/2c53e42a-f15f-4a04-86d4-57441eff8dcd)
![issue 2](https://github.com/qwek1/All-of-Create/assets/82753478/4fa96d94-9bd8-4f96-8c9b-9b8786d669e0)
![issue 1](https://github.com/qwek1/All-of-Create/assets/82753478/d95a6a4d-44ed-40c1-9fc7-6c376d312a5c)

**Comment by qwek1** [comment]
I suggest setting up a Forge 1.19.2 43.3.5 server first, then once thats running; shut it down and upload the mods and configs folder onto the server after. 

If it still crashes or have the questbook issue after doing that then send logs here please 😃

**Comment by Meilo14** [comment]
yeah ill try that and i come xD

**Comment by Meilo14** [comment]
its running dude

**Comment by Meilo14** [comment]
ty very much man, ty for ur time man, 
Here's the mistake I was making:
When translating the server to Vm, I started the server from the java file, starting the server from the .sh, everything started correctly. I imagine that it is something that anyone who understands the subject would be wise, but for me it has been a headache, if it were not for you, I would not have done it.
ty dude, I owe you a beer

**Comment by qwek1** [comment]
Glad you got it running, have fun! 😄
